-- جدار التهنئات — نفّذ هذا الملف في SQL Editor داخل مشروع Supabase

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  batch text not null default 'guest' check (batch in ('guest', 'cyberx', 'brainware')),
  message text not null check (char_length(message) between 1 and 280),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- القراءة للجميع
drop policy if exists "anon can read messages" on public.messages;
create policy "anon can read messages"
  on public.messages for select
  to anon
  using (true);

-- الكتابة للجميع (بدون تعديل أو حذف)
drop policy if exists "anon can insert messages" on public.messages;
create policy "anon can insert messages"
  on public.messages for insert
  to anon
  with check (true);

create index if not exists messages_created_at_idx on public.messages (created_at desc);
